language: java
jdk: openjdk8

env:
  - secure: "bhOqRALNNsbl0fUu9L6p8tZclPt8C1MPpFow5f5Qkz8pPdp2zvEF2P9ouxKsjDGeeyKRf+Jr/Zmz8bIVollth9Zbb2OqSa/SD0F7OnQl6w3f1RbYFJxrOgzkmBI89LGFvoMl2r5akqZCRF6b66TzB4J3H87XR3mlK78jFU41RJNtO6YSqCatzz0dJA3zoLaBF4666seAgRs3zlAz+rAWg96S5labOUzqIV/VAc3tZIHcwUmQHDOJBf0Ey1vJfYVWxrj5NI6gLaNmfr4sPlVOQEt7g8jh8jw9/b8czLDln5W49jJnzvsoVEuu4V4lHY9rDz5fCf1NovXLKm5YwwHC/QcFFNdR0az8Cwbkx9q2D1RhTfS4A4+eed19ItE36AhbjYzJqx5KwPe/cNTWSnHdEPR2S+H1tyYfmwNqHCzLmE3/a0p+hBJ1FlFs+9BD8ymJtDhYovgQ+QL25d1SmONdY1aB6G2zoiDPK3QFq+Xs2U3robXzt3zdiSVwb5nWfP3eDO3LvzAaugidt4wUDJ52rIyjkW/yChiLeDNefYeWZlWS5e25vYhTJpTEDoCmMj3i7d4PAzXTIHxKqMY9A7/jBUpsnXZ1v++VmuYzDCRTysH5h7Q7amd0roxok3A8MRN64HaX2XtibtVy8NYIkJviQXM+02pt9PNILVVs4kw0xAc="
  - "VAR2=var2"

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  #- git fetch --unshallow
  #- mvn clean verify -Pcoverage
  - set
  - echo "SONAR_TOKEN=$SONAR_TOKEN"
  #- mvn sonar:sonar -Dsonar.login=9eb0bca134fa54ff1f25adb6006c8957038241f5 -Dsonar.sourceEncoding=UTF-8 -Dsonar.branch.name=master