language: java
jdk: openjdk8

addons:
  sonarcloud:
    organization: "noemus"
    token:
      secure: "iu7PlTag5mF3niAnQ5BCRMdL7XUBoUtw5LQWznNqRrcG9aIkkAWJzriXnI66tVcXVsY7gBLOZAXd7hEjP9eNHIJefvWjpRIlFxvEuf7hCb7VOx3sC74nSmMT8XtxwOAn5TiE+QvJ0p/fHQTn6X7B0aA97YOVYG0Zpwl+ujb60gUlRD/9vhJm/BJMAtVkvSqOjuZuMSZOveW/6F9dx3tmqhfmVJPjtlrylZWnoKa4YARbguqWbvzJwEJEHbulHWuJOB7l5i0AxE5aIgcPZmUc5Z0y98oF5Zl7YquzgMqdjlPTcEyiNvqdbwnbKScs1UoBoV1/XgxpIKzf5aSjZII5OKQ2O+2bx82T2Kh8PYd9hViztfnks4enVxa2YPR8eEqnehmregvxkzYF/nMomFNZiR4t8Xruad8auIynFy8HNgCaaowEuNM1Rxs3mkK6MySY2coIGOMWNbQBP3Q+l5VCfwSUZ+teYyMAaOt+F7TvNU1kkwDCsOEZq3cVHX8vdECtM8PhY3Pp38jiqodloErEknU3wRIDaIICkfEc52qn7cV1r6vTkF/vbWjLnpc0oMX3OxKHLOZ1XQoGG90PKxw2pv4LBYyV42KVYg1q7A6XueLpA/y4uajWslbPlHfegKjKyfTDPDwvmugyJWa4iSSc5xAKDo4c9o1ehmm9JXqC6XU="

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean verify
  - mvn sonar:sonar -Dsonar.projectKey=noemus_neoxml