language: java
jdk: openjdk8

env:
  global:
    secure: ZZJOag7YKYDn1si4kurtpW9r0V3q2QrE64roAMg7Y4N/woBGYG4RuS4r36ApZRR41q/KjQAZ8KcISmL9Al50g+SE3N73sqJlQlx93pDQO2sVvFrFl8ToDcYXLgKmkJOGyBrBOFNx5Q//9KYzjETn67pdKF32si9wtVJjft2lwiREg8d/JkhMke0QByGNUmCVMlkg+RdhwsF2nUpui9FZabt1IRnbPcomTN7/+3sKyddfvjA3MbbTXu4k3X3wDPyU7vh5/UkKceQPlqBhr3wvP7PIrXr5yyj2a59QMEKNKSFZrB+FkfZkO3gFaIOCW0+TKhSvkTM+Yn7W4tlyu8UyI0aH6jqecppJl/swYAvdShnsz3xLpbvo8dd1SxTK231HYeBkBuAJrq56OFXnUtGkf3CnOL5VQCSvd8lvqt9Zrjua959y+eGEvxW8Hc7BttP9bsdxNfhbDK5IVyQi+DxJAj0NZKVhlvJS7FDcMAapDuCnD7OErE+PsqJo7wGofWLqt/hydF9egpOlUfBKmPv+hp0jsEMvBKo+N9qnbBgeNsbBPzc8B28S1yE9ap9FKumwMZGq/EK7NAxee7bm9takVs1Y4TfVUNvMymnB9OoznF7uEL2e2c2HpFqWiPOEi7oELIug0UL2Hno6XCZsGfEx0AINU3BXXANN8jyCCR7NnBs=

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - git fetch --unshallow
  - mvn clean verify -Pcoverage
  - echo $SONAR_TOKEN
  - mvn sonar:sonar -Dsonar.sourceEncoding=UTF-8 -Dsonar.branch.name=master