language: java
jdk: openjdk11

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - git fetch --unshallow
  - mvn clean verify -Pcoverage
  - echo "SONAR_TOKEN=$SONAR_TOKEN"
  - mvn sonar:sonar -Dsonar.login=$SONAR_TOKEN -Dsonar.sourceEncoding=UTF-8 -Dsonar.branch.name=master