language: java
jdk: openjdk8

addons:
  sonarcloud:
    organization: "noemus"
    token:
      secure: "SVE1nciW4CHsUfMCDQ3jeJERsuH5IZhxQ0xse7NStPZDpL5XJcBwneieypqF5frqz0/I6f19c13oTEHlg0LPkVJamuXa8gboa8bT+gqyxV5Q6YDM8n9b6lKelXY+9Pz+FZpHX0qfmdVneP7CrD15KorRzdir3Znzsmj6qvFAhXMJ93MFg7J3eGcjhM1EWX0EAddt1/PALYY4cszI20GBPDVymIH9lPrxX+Ksi4TeXnSnDQkW7vpDt2XVGI9w+fhltPV9j0Rau/7c9/hM2bzWcGSl9m6ZFcOXLayxIjNDt1Fwspxm1WQQKa4lP+R9LUFIAN+qSY+G6drTpMqfZPoQ4vLLA/XK4gndU4TaABio623yywXuRMJhGoVuUX9N5bEskEUwtnwz9R/8AN/lj7px5EDhPphVFld6shl3VzHopyp21v/dX4lowM/OSAq+Aru/UoZai1JRxFuG5arToALpP+Rjn+Gipcg2kD1aBJS6eGDK+knfGPnF8yI9CzC3Vg3knGPfzGAiBkj1wA4cvoacgbQyiyYJa6nYJpG1iH3pgRkEtLo6X2MT6Vosw0/7/tltrNzJ6gBTVwMKxqgFSQTrXAa7jknN75LsxsBrkrAc9v63Xcp8JWXFfiUFt12bcsOf/4G9wlFZaCNyz3dmvvoK/66hrl95xiEAZS0oTiHz82I="

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean verify
  - mvn sonar:sonar -Dsonar.projectKey=noemus_neoxml